// AUTO-GENERATED by tools/convert_connectome.py — do not edit
// C. elegans full hermaphrodite connectome, Cook et al. 2019
// (via OpenWorm c302: herm_full_edgelist_MODIFIED.csv + owmeta_cache.json)
#ifndef CONNECTOME_H
#define CONNECTOME_H

#include <stdint.h>

#define N_NEURONS       302
#define N_NODES         446
#define N_EDGES_CHEM    4666
#define N_EDGES_GAP     2577

enum { NODE_NEURON=0, NODE_BODY_MUSCLE, NODE_PHAR_MUSCLE,
       NODE_VULVAL_MUSCLE, NODE_UTERINE_MUSCLE, NODE_OTHER };
enum { F_SENSORY=1, F_INTER=2, F_MOTOR=4 };
enum { NT_NONE=0, NT_ACH, NT_GLU, NT_GABA, NT_DA, NT_5HT, NT_OCT, NT_TYR };

typedef struct {
    const char* name;   // canonical name e.g. "ASEL"
    uint8_t cls;        // NODE_*
    uint8_t func;       // F_* bitmask (neurons)
    int8_t  sign;       // +1 / -1 chemical output sign
    uint8_t nt;         // NT_* neurotransmitter
} NodeMeta;

typedef struct { uint16_t src, dst; uint8_t w; } SynEdge;

extern const NodeMeta node_meta[N_NODES];
extern const SynEdge chem_edges[N_EDGES_CHEM];
extern const SynEdge gap_edges[N_EDGES_GAP];

int node_index(const char* name);

#endif // CONNECTOME_H
